apiVersion: anynines.com/v1
kind: Backup
metadata:
  name: backup-example-pg-instance
  namespace: default
spec:
  instanceRef: example-pg-instance
  serviceInstanceType: postgresql
  compositionRef:
    name: a8s-backup