apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - https://raw.githubusercontent.com/anynines/klutchio/v1.3.0/crossplane-api/deploy/functions/function-patch-and-transform.yaml