apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: dex
    port: 5556
    targetPort: 5556
  - protocol: TCP
    name: telemetry
    port: 5558
    targetPort: 5558
  selector:
    app: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
spec:
  selector:
    matchLabels:
      app: dex
  replicas: 1
  template:
    metadata:
      labels:
        app: dex
    spec:
      containers:
      - name: dex
        image: dexidp/dex:v2.42.0-distroless
        args:
        - dex
        - serve
        - /conf/dex/config.yaml
        resources:
          requests: {cpu: 100m, memory: 64Mi}
          limits: {cpu: 400m, memory: 256Mi}
        env:
        - name: DEX_ISSUER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-config
              key: OIDC-ISSUER-CLIENT-SECRET
        - name: DEX_ISSUER_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oidc-config
              key: OIDC-ISSUER-CLIENT-ID
        ports:
        - containerPort: 5556
          name: dex
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        - name: config
          mountPath: /conf/dex
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dex-config
      - name: data
        emptyDir: {}
