apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - crossplane-core-namespace.yaml
helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.19.0
    releaseName: crossplane
    namespace: crossplane-system
    valuesInline:
      args:
        - "--enable-ssa-claims"
