apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - https://raw.githubusercontent.com/anynines/klutchio/v1.3.0/bind/deploy/resources/namespace.yaml
  - crds
  - export-templates
  - klutch-bind-backend-runtime