# klutch-install/overlays/aws/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - ingress-nginx-namespace.yaml

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.13.0
  releaseName: ingress-nginx
  namespace: ingress-nginx
  # This tells Kustomize to use the dedicated values file.
  valuesFile: ingress-nginx-values.yaml 