# This is a template, DO NOT APPLY DIRECTLY.

apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: minio-dev
type: Opaque
stringData:
  rootUser: "YOUR_MINIO_ROOT_USER"
  rootPassword: "YOUR_VERY_SECRET_PASSWORD"
