issuer: http://host.lima.internal/dex

storage: {type: memory}
web: {http: 0.0.0.0:5556}
telemetry: {http: 0.0.0.0:5558}
grpc: {addr: 0.0.0.0:5557}
staticClients:
  - idEnv: DEX_ISSUER_CLIENT_ID
    redirectURIs: ['http://host.lima.internal/callback']
    name: 'Kube Bind'
    secretEnv: DEX_ISSUER_CLIENT_SECRET
enablePasswordDB: true
staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"