apiVersion: v1
kind: ConfigMap
metadata:
  name: a8s-backup-store-config
  namespace: a8s-system
data:
  backup-store-config.yaml: |
    config:
      cloud_configuration:
        provider: AWS
        container: a8s-backups
        region: eu-central-1
        endpoint: http://minio.minio-dev.svc.cluster.local:9000
        path_style: true

---
apiVersion: v1
kind: Secret
metadata:
  name: a8s-backup-storage-credentials
  namespace: a8s-system
type: Opaque
stringData:
  access-key-id: minioadmin
  secret-access-key: minioadmin
  encryption-password: "C9v%EL5a4PZpM8zNXqfHlxAuGR&|OJ/>ny^kWI0he21VY*#ob3g-c+K7TtSrmw6s"
