apiVersion: v1
kind: Secret
metadata:
  name: oidc-config
  namespace: bind
type: Opaque
stringData:
  oidc-issuer-client-id: "kube-bind"
  oidc-issuer-client-secret: "aebca00f17a4940aa0569597"
  oidc-issuer-url: "http://klutch.apps-crc.testing/dex"
  oidc-callback-url: "http://klutch.apps-crc.testing/callback"
