kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: crossplane-fn-unrestricted
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
groups:
- system:serviceaccounts:crossplane-system
