apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# This Kustomization ONLY handles resources in the crossplane-system namespace.
namespace: crossplane-system

resources:
  # Inherit the base crossplane namespace resource
  # Add the SCC from the parent overlay directory
  - crossplane-security-constraints.yaml

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.19.0
    releaseName: crossplane
    # The namespace here now matches the top-level namespace, so there's no conflict.
    namespace: crossplane-system
    valuesInline:
      args:
        - "--enable-ssa-claims"
    valuesFile: crossplane-values.yaml # Reference the values file in the parent directory